class Serial:
    def __init__(self, path: str, baudrate: int, *, timeout: float) -> None: ...

    def read(self, count: int) -> bytes: ...

    def write(self, data: bytes) -> None: ...

    def close(self) -> None: ...
